[workspace]
authors = ["sounddrill31 <84176052+sounddrill31@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "alice"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
libsmu = ">=1.0.3,<2"
tk = ">=8.6.13,<9"
matplotlib = ">=3.10.5,<4"
numpy = ">=2.2.6,<3"
