[workspace]
authors = ["sounddrill31 <84176052+sounddrill31@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "alice"
platforms = ["win-64", "linux-64", "osx-64"]
version = "1.3.0"

[tasks]
udev-setup = "python install_udev_rule.py"
start = "python alice-desktop*.pyw"

[dependencies]
libsmu = ">=1.0.3,<2"
tk = ">=8.6.13,<9"
matplotlib = ">=3.10.5,<4"
numpy = ">=2.2.6,<3"
